### ISSUE TITLE
retardo mental

### ISSUE THREAD

**Issue by zingotaku** [davizinmaker/tdmclient#2]
pq karalhos vc obfuscou um código que tá na poha do github

**Comment by JKMAKER** [comment]
que q eu fiz mann

Em sáb., 4 de set. de 2021 01:35, Zing ***@***.***> escreveu:

**Comment by davizinmaker** [comment]
> pq karalhos vc obfuscou um código que tá na poha do github

evitar skid

**Comment by JKMAKER** [comment]
porr se tu vier com papo torto vo banir seu email krlh


Em sáb., 4 de set. de 2021 15:37, maquiagens ***@***.***>
escreveu:
